version: '2'
services:
  jhipstersampleapplicationwithredis-app:
    image: jhipstersampleapplicationwithredis
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationwithredis-mysql:3306/jhipstersampleapplicationwithredis?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_CACHE_REDIS_SERVER=redis://jhipstersampleapplicationwithredis-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://jhipstersampleapplicationwithredis-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplicationwithredis-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplicationwithredis-mysql
  jhipstersampleapplicationwithredis-redis:
    extends:
      file: redis.yml
      service: jhipstersampleapplicationwithredis-redis
